### ISSUE TITLE
Swap Filter/FilterInverted Icons: Favourites, Recently Added/Played

### ISSUE THREAD

**Issue by S34NN** [Kosnix/PS5Like#1]
I noticed the filter icons for Favourites, Recently Added, and Recently Played need to be switched between the Filter and FilterInverted folders, otherwise it results in a solid white or black colored circle for the filter style rather than showing the proper icons.

I confirmed this yesterday when testing this fix manually which worked to display the icons properly, but has now reverted upon today's 2.0.0 update. Not sure if there is another solution to this with editing something else with the theme styling, but I will fix this manually for the time being.

Also, though not necessarily an issue, I had to duplicate some of the icons with alternate naming such as Favorites (region dependent, I understand), or edit the name of the saved filter to match the filter image naming (for example my filter for All Games was named "All"). Perhaps this will assist someone else who sees this.

**Comment by Kosnix** [comment]
it's weird, for me the icons are the right color.  If I reverse the icons, I would have the same problem as you.  I will ask on discord if you are the only one with this problem

**Comment by S34NN** [comment]
Yeah, that's odd. Here's a screenshot of my current filters after swapping the icon images like I mentioned (with Favorites being the currently selected filter).

![filters](https://user-images.githubusercontent.com/42592447/200053538-7c3cc5cc-592a-42cd-835f-eb49f6c5f0b6.jpg)

**Comment by Kosnix** [comment]
it's ok I got it.  the next update will fix the problem
